name: API Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_api_collection:
    name: Run Insomnia API Collection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Print working directory
        run: pwd
      - name: Setup inso
        uses: kong/setup-inso@v2
        with:
          inso-version: 10.3.1

      - name: Print inso version
        run: inso --version

      - name: Run Insomnia API Collection
        # run: inso run collection Tadeu-QualityEagles-Collection -w ./Tadeu-QualityEagles-Collection-with-bug-fixes-inso-v4.yaml --reporter spec
        run: inso run collection Tadeu-QualityEagles-Collection -w ./Tadeu-QualityEagles-Collection-with-bug-fixes-inso-v4.yaml --reporter-junit-export junit-report.xml

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: junit_report.xml